version: '3.8'

services:
  back-end:
    build:
      context: .
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task4
    ports:
      - "5252:5252"
    depends_on:
      - front-end

  front-end:
    build:
      context: .
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task4
    ports:
      - "80:80"